name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag fastsend:$(date +%s)
        docker build . --file Dockerfile2 --tag fastsend:$(date +%s)-slim
        docker images

