name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: down slim
        run: |
          curl -L -o ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/1.40.11/dist_linux.tar.gz
          tar -xvf ds.tar.gz
          mv  dist_linux/slim /usr/local/bin/
          mv  dist_linux/* /usr/local/bin/

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile2 --tag fastsend:latest
          docker images
          

      - name: docker slim
        run: |
          slim build fastsend:latest
          docker images

      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3